### ISSUE TITLE
React Dazzle V2 Roadmap

### ISSUE THREAD

**Issue by Raathigesh** [Raathigesh/dazzle#15]
Following are the ideas I have for the next major version of dazzle. 

- [ ] Rewrite using typescript
- [ ] Use Jest for unit testing
- [ ] Move away from grid based layout and use [react grid layout](https://github.com/STRML/react-grid-layout) (#12)
- [ ] Use [styled components](https://github.com/styled-components/styled-components)
- [ ] Make dazzle more modular and have plugins.

### Plugins
Modularize certain UI components as plugins. The plugins I could think of right now are
- Add widget dialog
- Widget full-screen mode
- Widget configuration dialog

Do you have any ideas or improvements? Let discuss!
